sudo: false
language: node_js
node_js:
  - '6'
  - '7'
addons:
  - postgresql: '9.3'
script:
  - TEST_TIMEOUT=60000 CNPM_SOURCE_NPM=https://registry.npmjs.org CNPM_SOURCE_NPM_ISCNPM=false npm run test-all
after_script:
  - npm i codecov && codecov
